# Generated by Django 3.1.2 on 2020-10-27 01:55

import BackendManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='phone_number')),
                ('self_pics', models.ImageField(upload_to=BackendManagement.models.user_directory_path, verbose_name='self_pics')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='phone_number')),
            ],
            options={
                'db_table': 'Saler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('link', models.URLField(default='https://www.taobao.com', max_length=255, verbose_name='link')),
                ('overall_score', models.FloatField(default=0, verbose_name='overall_score')),
                ('number_people_scoring', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='number_people_scoring')),
                ('owned_saler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendManagement.saler')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
