# Generated by Django 3.1.2 on 2020-11-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendManagement', '0004_auto_20201111_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
