# Generated by Django 3.1.2 on 2020-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendManagement', '0006_auto_20201111_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='phone_number'),
        ),
    ]
